# Generated by Django 5.2.7 on 2025-10-15 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
