# Generated by Django 5.2.7 on 2025-11-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_room', '0003_room_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
